package com.teammetallurgy.metallurgy6.objects.items;

import com.google.common.collect.Lists;
import com.teammetallurgy.metallurgy6.MetallurgyMain;
import com.teammetallurgy.metallurgy6.util.MetallurgyItemTier;
import net.minecraft.item.*;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.ObjectHolder;

import java.util.List;

@ObjectHolder(MetallurgyMain.MOD_ID)
@Mod.EventBusSubscriber(modid = MetallurgyMain.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class MetallurgyItems {

    public static List<Item> ITEMS = Lists.newArrayList();

    public static final Item TEST_PICKAXE = register("test_pickaxe", new PickaxeItem(MetallurgyItemTier.TEST_TIER, 0, 2.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item TEST_SHOVEL = register("test_shovel", new ShovelItem(MetallurgyItemTier.TEST_TIER, 0, 2.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item TEST_SWORD = register("test_sword", new SwordItem(MetallurgyItemTier.TEST_TIER, 0, 2.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item TEST_HOE = register("test_hoe", new HoeItem(MetallurgyItemTier.TEST_TIER, 0, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item TEST_AXE = register("test_axe", new AxeItem(MetallurgyItemTier.TEST_TIER, 0, 2.0F, new Item.Properties().group(MetallurgyMain.GROUP)));

    public static final Item SLAG_PICKAXE = register("slag_pickaxe", new PickaxeItem(MetallurgyItemTier.SLAG, 2, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SLAG_AXE = register("slag_axe", new AxeItem(MetallurgyItemTier.SLAG, 7, -3.2F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SLAG_SHOVEL = register("slag_shovel", new ShovelItem(MetallurgyItemTier.SLAG, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SLAG_SWORD = register("slag_sword", new SwordItem(MetallurgyItemTier.SLAG, 4, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SLAG_HOE = register("slag_hoe", new HoeItem(MetallurgyItemTier.SLAG, -2.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item COPPER_PICKAXE = register("copper_pickaxe", new PickaxeItem(MetallurgyItemTier.COPPER, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item COPPER_AXE = register("copper_axe", new AxeItem(MetallurgyItemTier.COPPER, 7, -3.2F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item COPPER_SHOVEL = register("copper_shovel", new ShovelItem(MetallurgyItemTier.COPPER, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item COPPER_SWORD = register("copper_sword", new SwordItem(MetallurgyItemTier.COPPER, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item COPPER_HOE = register("copper_hoe", new HoeItem(MetallurgyItemTier.COPPER, -2.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item TIN_PICKAXE = register("tin_pickaxe", new PickaxeItem(MetallurgyItemTier.TIN, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item TIN_AXE = register("tin_axe", new AxeItem(MetallurgyItemTier.TIN, 7, -3.2F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item TIN_SHOVEL = register("tin_shovel", new ShovelItem(MetallurgyItemTier.TIN, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item TIN_SWORD = register("tin_sword", new SwordItem(MetallurgyItemTier.TIN, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item TIN_HOE = register("tin_hoe", new HoeItem(MetallurgyItemTier.TIN, -2.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRONZE_PICKAXE = register("bronze_pickaxe", new PickaxeItem(MetallurgyItemTier.BRONZE, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRONZE_AXE = register("bronze_axe", new AxeItem(MetallurgyItemTier.BRONZE, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRONZE_SHOVEL = register("bronze_shovel", new ShovelItem(MetallurgyItemTier.BRONZE, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRONZE_SWORD = register("bronze_sword", new SwordItem(MetallurgyItemTier.BRONZE, 3, -2.3F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRONZE_HOE = register("bronze_hoe", new HoeItem(MetallurgyItemTier.BRONZE, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item LEAD_PICKAXE = register("lead_pickaxe", new PickaxeItem(MetallurgyItemTier.LEAD, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item LEAD_AXE = register("lead_axe", new AxeItem(MetallurgyItemTier.LEAD, 6, -3.3F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item LEAD_SHOVEL = register("lead_shovel", new ShovelItem(MetallurgyItemTier.LEAD, 2, -3.5F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item LEAD_SWORD = register("lead_sword", new SwordItem(MetallurgyItemTier.LEAD, 4, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item LEAD_HOE = register("lead_hoe", new HoeItem(MetallurgyItemTier.LEAD, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MYCELITE_PICKAXE = register("mycelite_pickaxe", new PickaxeItem(MetallurgyItemTier.MYCELITE, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MYCELITE_AXE = register("mycelite_axe", new AxeItem(MetallurgyItemTier.MYCELITE, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MYCELITE_SHOVEL = register("mycelite_shovel", new ShovelItem(MetallurgyItemTier.MYCELITE, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MYCELITE_SWORD = register("mycelite_sword", new SwordItem(MetallurgyItemTier.MYCELITE, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MYCELITE_HOE = register("mycelite_hoe", new HoeItem(MetallurgyItemTier.MYCELITE, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item THOKCHA_PICKAXE = register("thokcha_pickaxe", new PickaxeItem(MetallurgyItemTier.THOKCHA, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item THOKCHA_AXE = register("thokcha_axe", new AxeItem(MetallurgyItemTier.THOKCHA, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item THOKCHA_SHOVEL = register("thokcha_shovel", new ShovelItem(MetallurgyItemTier.THOKCHA, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item THOKCHA_SWORD = register("thokcha_sword", new SwordItem(MetallurgyItemTier.THOKCHA, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item THOKCHA_HOE = register("thokcha_hoe", new HoeItem(MetallurgyItemTier.THOKCHA, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_PICKAXE = register("nickel_pickaxe", new PickaxeItem(MetallurgyItemTier.NICKEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_AXE = register("nickel_axe", new AxeItem(MetallurgyItemTier.NICKEL, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_SHOVEL = register("nickel_shovel", new ShovelItem(MetallurgyItemTier.NICKEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_SWORD = register("nickel_sword", new SwordItem(MetallurgyItemTier.NICKEL, 3, -2.2F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_HOE = register("nickel_hoe", new HoeItem(MetallurgyItemTier.NICKEL, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CUPRONICKEL_PICKAXE = register("cupronickel_pickaxe", new PickaxeItem(MetallurgyItemTier.CUPRONICKEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CUPRONICKEL_AXE = register("cupronickel_axe", new AxeItem(MetallurgyItemTier.CUPRONICKEL, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CUPRONICKEL_SHOVEL = register("cupronickel_shovel", new ShovelItem(MetallurgyItemTier.CUPRONICKEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CUPRONICKEL_SWORD = register("cupronickel_sword", new SwordItem(MetallurgyItemTier.CUPRONICKEL, 3, -2.2F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CUPRONICKEL_HOE = register("cupronickel_hoe", new HoeItem(MetallurgyItemTier.CUPRONICKEL, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MONEL_PICKAXE = register("monel_pickaxe", new PickaxeItem(MetallurgyItemTier.MONEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MONEL_AXE = register("monel_axe", new AxeItem(MetallurgyItemTier.MONEL, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MONEL_SHOVEL = register("monel_shovel", new ShovelItem(MetallurgyItemTier.MONEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MONEL_SWORD = register("monel_sword", new SwordItem(MetallurgyItemTier.MONEL, 3, -2.2F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MONEL_HOE = register("monel_hoe", new HoeItem(MetallurgyItemTier.MONEL, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CROWN_GOLD_PICKAXE = register("crown_gold_pickaxe", new PickaxeItem(MetallurgyItemTier.CROWN_GOLD, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CROWN_GOLD_AXE = register("crown_gold_axe", new AxeItem(MetallurgyItemTier.CROWN_GOLD, 6, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CROWN_GOLD_SHOVEL = register("crown_gold_shovel", new ShovelItem(MetallurgyItemTier.CROWN_GOLD, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CROWN_GOLD_SWORD = register("crown_gold_sword", new SwordItem(MetallurgyItemTier.CROWN_GOLD, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CROWN_GOLD_HOE = register("crown_gold_hoe", new HoeItem(MetallurgyItemTier.CROWN_GOLD, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WHITE_GOLD_PICKAXE = register("white_gold_pickaxe", new PickaxeItem(MetallurgyItemTier.WHITE_GOLD, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WHITE_GOLD_AXE = register("white_gold_axe", new AxeItem(MetallurgyItemTier.WHITE_GOLD, 6, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WHITE_GOLD_SHOVEL = register("white_gold_shovel", new ShovelItem(MetallurgyItemTier.WHITE_GOLD, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WHITE_GOLD_SWORD = register("white_gold_sword", new SwordItem(MetallurgyItemTier.WHITE_GOLD, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WHITE_GOLD_HOE = register("white_gold_hoe", new HoeItem(MetallurgyItemTier.WHITE_GOLD, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PEWTER_PICKAXE = register("pewter_pickaxe", new PickaxeItem(MetallurgyItemTier.PEWTER, 1, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PEWTER_AXE = register("pewter_axe", new AxeItem(MetallurgyItemTier.PEWTER, 6, -3.3F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PEWTER_SHOVEL = register("pewter_shovel", new ShovelItem(MetallurgyItemTier.PEWTER, 2, -3.5F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PEWTER_SWORD = register("pewter_sword", new SwordItem(MetallurgyItemTier.PEWTER, 4, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PEWTER_HOE = register("pewter_hoe", new HoeItem(MetallurgyItemTier.PEWTER, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MOLYBDOCHALKOS_PICKAXE = register("molybdochalkos_pickaxe", new PickaxeItem(MetallurgyItemTier.MOLYBDOCHALKOS, 1, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MOLYBDOCHALKOS_AXE = register("molybdochalkos_axe", new AxeItem(MetallurgyItemTier.MOLYBDOCHALKOS, 6, -3.3F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MOLYBDOCHALKOS_SHOVEL = register("molybdochalkos_shovel", new ShovelItem(MetallurgyItemTier.MOLYBDOCHALKOS, 2, -3.5F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MOLYBDOCHALKOS_SWORD = register("molybdochalkos_sword", new SwordItem(MetallurgyItemTier.MOLYBDOCHALKOS, 4, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MOLYBDOCHALKOS_HOE = register("molybdochalkos_hoe", new HoeItem(MetallurgyItemTier.MOLYBDOCHALKOS, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEPATIZON_PICKAXE = register("hepatizon_pickaxe", new PickaxeItem(MetallurgyItemTier.HEPATIZON, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEPATIZON_AXE = register("hepatizon_axe", new AxeItem(MetallurgyItemTier.HEPATIZON, 6, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEPATIZON_SHOVEL = register("hepatizon_shovel", new ShovelItem(MetallurgyItemTier.HEPATIZON, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEPATIZON_SWORD = register("hepatizon_sword", new SwordItem(MetallurgyItemTier.HEPATIZON, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEPATIZON_HOE = register("hepatizon_hoe", new HoeItem(MetallurgyItemTier.HEPATIZON, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ANGMALLEN_PICKAXE = register("angmallen_pickaxe", new PickaxeItem(MetallurgyItemTier.ANGMALLEN, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ANGMALLEN_AXE = register("angmallen_axe", new AxeItem(MetallurgyItemTier.ANGMALLEN, 6, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ANGMALLEN_SHOVEL = register("angmallen_shovel", new ShovelItem(MetallurgyItemTier.ANGMALLEN, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ANGMALLEN_SWORD = register("angmallen_sword", new SwordItem(MetallurgyItemTier.ANGMALLEN, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ANGMALLEN_HOE = register("angmallen_hoe", new HoeItem(MetallurgyItemTier.ANGMALLEN, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_PICKAXE = register("manganese_pickaxe", new PickaxeItem(MetallurgyItemTier.MANGANESE, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_AXE = register("manganese_axe", new AxeItem(MetallurgyItemTier.MANGANESE, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_SHOVEL = register("manganese_shovel", new ShovelItem(MetallurgyItemTier.MANGANESE, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_SWORD = register("manganese_sword", new SwordItem(MetallurgyItemTier.MANGANESE, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_HOE = register("manganese_hoe", new HoeItem(MetallurgyItemTier.MANGANESE, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEAVY_STEEL_PICKAXE = register("heavy_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.HEAVY_STEEL, 1, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEAVY_STEEL_AXE = register("heavy_steel_axe", new AxeItem(MetallurgyItemTier.HEAVY_STEEL, 6, -3.3F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEAVY_STEEL_SHOVEL = register("heavy_steel_shovel", new ShovelItem(MetallurgyItemTier.HEAVY_STEEL, 2, -3.5F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEAVY_STEEL_SWORD = register("heavy_steel_sword", new SwordItem(MetallurgyItemTier.HEAVY_STEEL, 4, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item HEAVY_STEEL_HOE = register("heavy_steel_hoe", new HoeItem(MetallurgyItemTier.HEAVY_STEEL, -1.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item DAMASCUS_STEEL_PICKAXE = register("damascus_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.DAMASCUS_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item DAMASCUS_STEEL_AXE = register("damascus_steel_axe", new AxeItem(MetallurgyItemTier.DAMASCUS_STEEL, 5, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item DAMASCUS_STEEL_SHOVEL = register("damascus_steel_shovel", new ShovelItem(MetallurgyItemTier.DAMASCUS_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item DAMASCUS_STEEL_SWORD = register("damascus_steel_sword", new SwordItem(MetallurgyItemTier.DAMASCUS_STEEL, 3, -2.3F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item DAMASCUS_STEEL_HOE = register("damascus_steel_hoe", new HoeItem(MetallurgyItemTier.DAMASCUS_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_STEEL_PICKAXE = register("manganese_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.MANGANESE_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_STEEL_AXE = register("manganese_steel_axe", new AxeItem(MetallurgyItemTier.MANGANESE_STEEL, 5, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_STEEL_SHOVEL = register("manganese_steel_shovel", new ShovelItem(MetallurgyItemTier.MANGANESE_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_STEEL_SWORD = register("manganese_steel_sword", new SwordItem(MetallurgyItemTier.MANGANESE_STEEL, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item MANGANESE_STEEL_HOE = register("manganese_steel_hoe", new HoeItem(MetallurgyItemTier.MANGANESE_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_STEEL_PICKAXE = register("nickel_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.NICKEL_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_STEEL_AXE = register("nickel_steel_axe", new AxeItem(MetallurgyItemTier.NICKEL_STEEL, 5, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_STEEL_SHOVEL = register("nickel_steel_shovel", new ShovelItem(MetallurgyItemTier.NICKEL_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_STEEL_SWORD = register("nickel_steel_sword", new SwordItem(MetallurgyItemTier.NICKEL_STEEL, 3, -2.2F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item NICKEL_STEEL_HOE = register("nickel_steel_hoe", new HoeItem(MetallurgyItemTier.NICKEL_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item FUNGAL_STEEL_PICKAXE = register("fungal_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.FUNGAL_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item FUNGAL_STEEL_AXE = register("fungal_steel_axe", new AxeItem(MetallurgyItemTier.FUNGAL_STEEL, 5, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item FUNGAL_STEEL_SHOVEL = register("fungal_steel_shovel", new ShovelItem(MetallurgyItemTier.FUNGAL_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item FUNGAL_STEEL_SWORD = register("fungal_steel_sword", new SwordItem(MetallurgyItemTier.FUNGAL_STEEL, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item FUNGAL_STEEL_HOE = register("fungal_steel_hoe", new HoeItem(MetallurgyItemTier.FUNGAL_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item METEOR_STEEL_PICKAXE = register("meteor_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.METEOR_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item METEOR_STEEL_AXE = register("meteor_steel_axe", new AxeItem(MetallurgyItemTier.METEOR_STEEL, 5, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item METEOR_STEEL_SHOVEL = register("meteor_steel_shovel", new ShovelItem(MetallurgyItemTier.METEOR_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item METEOR_STEEL_SWORD = register("meteor_steel_sword", new SwordItem(MetallurgyItemTier.METEOR_STEEL, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item METEOR_STEEL_HOE = register("meteor_steel_hoe", new HoeItem(MetallurgyItemTier.METEOR_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WOVEN_STEEL_PICKAXE = register("woven_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.WOVEN_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WOVEN_STEEL_AXE = register("woven_steel_axe", new AxeItem(MetallurgyItemTier.WOVEN_STEEL, 6, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WOVEN_STEEL_SHOVEL = register("woven_steel_shovel", new ShovelItem(MetallurgyItemTier.WOVEN_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WOVEN_STEEL_SWORD = register("woven_steel_sword", new SwordItem(MetallurgyItemTier.WOVEN_STEEL, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item WOVEN_STEEL_HOE = register("woven_steel_hoe", new HoeItem(MetallurgyItemTier.WOVEN_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ZINC_PICKAXE = register("zinc_pickaxe", new PickaxeItem(MetallurgyItemTier.ZINC, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ZINC_AXE = register("zinc_axe", new AxeItem(MetallurgyItemTier.ZINC, 7, -3.2F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ZINC_SHOVEL = register("zinc_shovel", new ShovelItem(MetallurgyItemTier.ZINC, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ZINC_SWORD = register("zinc_sword", new SwordItem(MetallurgyItemTier.ZINC, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ZINC_HOE = register("zinc_hoe", new HoeItem(MetallurgyItemTier.ZINC, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRASS_PICKAXE = register("brass_pickaxe", new PickaxeItem(MetallurgyItemTier.BRASS, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRASS_AXE = register("brass_axe", new AxeItem(MetallurgyItemTier.BRASS, 6, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRASS_SHOVEL = register("brass_shovel", new ShovelItem(MetallurgyItemTier.BRASS, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRASS_SWORD = register("brass_sword", new SwordItem(MetallurgyItemTier.BRASS, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item BRASS_HOE = register("brass_hoe", new HoeItem(MetallurgyItemTier.BRASS, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SILVER_PICKAXE = register("silver_pickaxe", new PickaxeItem(MetallurgyItemTier.SILVER, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SILVER_AXE = register("silver_axe", new AxeItem(MetallurgyItemTier.SILVER, 6, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SILVER_SHOVEL = register("silver_shovel", new ShovelItem(MetallurgyItemTier.SILVER, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SILVER_SWORD = register("silver_sword", new SwordItem(MetallurgyItemTier.SILVER, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SILVER_HOE = register("silver_hoe", new HoeItem(MetallurgyItemTier.SILVER, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PLATINUM_PICKAXE = register("platinum_pickaxe", new PickaxeItem(MetallurgyItemTier.PLATINUM, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PLATINUM_AXE = register("platinum_axe", new AxeItem(MetallurgyItemTier.PLATINUM, 6, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PLATINUM_SHOVEL = register("platinum_shovel", new ShovelItem(MetallurgyItemTier.PLATINUM, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PLATINUM_SWORD = register("platinum_sword", new SwordItem(MetallurgyItemTier.PLATINUM, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PLATINUM_HOE = register("platinum_hoe", new HoeItem(MetallurgyItemTier.PLATINUM, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ROSE_GOLD_PICKAXE = register("rose_gold_pickaxe", new PickaxeItem(MetallurgyItemTier.ROSE_GOLD, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ROSE_GOLD_AXE = register("rose_gold_axe", new AxeItem(MetallurgyItemTier.ROSE_GOLD, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ROSE_GOLD_SHOVEL = register("rose_gold_shovel", new ShovelItem(MetallurgyItemTier.ROSE_GOLD, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ROSE_GOLD_SWORD = register("rose_gold_sword", new SwordItem(MetallurgyItemTier.ROSE_GOLD, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ROSE_GOLD_HOE = register("rose_gold_hoe", new HoeItem(MetallurgyItemTier.ROSE_GOLD, -1.5F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ELECTRUM_PICKAXE = register("electrum_pickaxe", new PickaxeItem(MetallurgyItemTier.ELECTRUM, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ELECTRUM_AXE = register("electrum_axe", new AxeItem(MetallurgyItemTier.ELECTRUM, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ELECTRUM_SHOVEL = register("electrum_shovel", new ShovelItem(MetallurgyItemTier.ELECTRUM, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ELECTRUM_SWORD = register("electrum_sword", new SwordItem(MetallurgyItemTier.ELECTRUM, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ELECTRUM_HOE = register("electrum_hoe", new HoeItem(MetallurgyItemTier.ELECTRUM, -1.5F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ARGENTAN_PICKAXE = register("argentan_pickaxe", new PickaxeItem(MetallurgyItemTier.ARGENTAN, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ARGENTAN_AXE = register("argentan_axe", new AxeItem(MetallurgyItemTier.ARGENTAN, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ARGENTAN_SHOVEL = register("argentan_shovel", new ShovelItem(MetallurgyItemTier.ARGENTAN, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ARGENTAN_SWORD = register("argentan_sword", new SwordItem(MetallurgyItemTier.ARGENTAN, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item ARGENTAN_HOE = register("argentan_hoe", new HoeItem(MetallurgyItemTier.ARGENTAN, -1.5F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item RHODITE_PICKAXE = register("rhodite_pickaxe", new PickaxeItem(MetallurgyItemTier.RHODITE, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item RHODITE_AXE = register("rhodite_axe", new AxeItem(MetallurgyItemTier.RHODITE, 6, -3.1F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item RHODITE_SHOVEL = register("rhodite_shovel", new ShovelItem(MetallurgyItemTier.RHODITE, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item RHODITE_SWORD = register("rhodite_sword", new SwordItem(MetallurgyItemTier.RHODITE, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item RHODITE_HOE = register("rhodite_hoe", new HoeItem(MetallurgyItemTier.RHODITE, -1.5F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CORINTHIAN_STEEL_PICKAXE = register("corinthian_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.CORINTHIAN_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CORINTHIAN_STEEL_AXE = register("corinthian_steel_axe", new AxeItem(MetallurgyItemTier.CORINTHIAN_STEEL, 5, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CORINTHIAN_STEEL_SHOVEL = register("corinthian_steel_shovel", new ShovelItem(MetallurgyItemTier.CORINTHIAN_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CORINTHIAN_STEEL_SWORD = register("corinthian_steel_sword", new SwordItem(MetallurgyItemTier.CORINTHIAN_STEEL, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item CORINTHIAN_STEEL_HOE = register("corinthian_steel_hoe", new HoeItem(MetallurgyItemTier.CORINTHIAN_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SHIMMER_STEEL_PICKAXE = register("shimmer_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.SHIMMER_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SHIMMER_STEEL_AXE = register("shimmer_steel_axe", new AxeItem(MetallurgyItemTier.SHIMMER_STEEL, 5, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SHIMMER_STEEL_SHOVEL = register("shimmer_steel_shovel", new ShovelItem(MetallurgyItemTier.SHIMMER_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SHIMMER_STEEL_SWORD = register("shimmer_steel_sword", new SwordItem(MetallurgyItemTier.SHIMMER_STEEL, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item SHIMMER_STEEL_HOE = register("shimmer_steel_hoe", new HoeItem(MetallurgyItemTier.SHIMMER_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item KINGS_STEEL_PICKAXE = register("kings_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.KINGS_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item KINGS_STEEL_AXE = register("kings_steel_axe", new AxeItem(MetallurgyItemTier.KINGS_STEEL, 6, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item KINGS_STEEL_SHOVEL = register("kings_steel_shovel", new ShovelItem(MetallurgyItemTier.KINGS_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item KINGS_STEEL_SWORD = register("kings_steel_sword", new SwordItem(MetallurgyItemTier.KINGS_STEEL, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item KINGS_STEEL_HOE = register("kings_steel_hoe", new HoeItem(MetallurgyItemTier.KINGS_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PURE_STEEL_PICKAXE = register("pure_steel_pickaxe", new PickaxeItem(MetallurgyItemTier.PURE_STEEL, 1, -2.8F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PURE_STEEL_AXE = register("pure_steel_axe", new AxeItem(MetallurgyItemTier.PURE_STEEL, 7, -2.6F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PURE_STEEL_SHOVEL = register("pure_steel_shovel", new ShovelItem(MetallurgyItemTier.PURE_STEEL, 1.5F, -3.0F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PURE_STEEL_SWORD = register("pure_steel_sword", new SwordItem(MetallurgyItemTier.PURE_STEEL, 3, -2.4F, new Item.Properties().group(MetallurgyMain.GROUP)));
    public static final Item PURE_STEEL_HOE = register("pure_steel_hoe", new HoeItem(MetallurgyItemTier.PURE_STEEL, 0.0F, new Item.Properties().group(MetallurgyMain.GROUP)));


    private static Item register(String registryName, Item thisItem){
        thisItem.setRegistryName(registryName);
        ITEMS.add(thisItem);

        return thisItem;
    }

    @SubscribeEvent
    public static void registerItems(final RegistryEvent.Register<Item> event){
        for(Item thisItem : ITEMS){
            event.getRegistry().register(thisItem);
        }
    }
}
